import { createClient } from "jsr:@supabase/supabase-js@2";
interface BrandingRow { logo_url: string | null; sender_photo_url: string | null; sender_name: string | null; email_signature: string | null; primary_color: string; button_color: string; text_color: string; footer_text: string | null; }
interface EmailContent { subject: string; body: string; ctaLabel?: string; ctaUrl?: string; churchName?: string; }
export async function buildBrandedEmail(tenantId: string, content: EmailContent): Promise<{ html: string; subject: string }> {
  const supabase = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
  const { data: branding } = await supabase.from("email_branding").select("logo_url,sender_photo_url,sender_name,email_signature,primary_color,button_color,text_color,footer_text").eq("tenant_id", tenantId).maybeSingle();
  const b: BrandingRow = branding ?? { logo_url: null, sender_photo_url: null, sender_name: null, email_signature: null, primary_color: "#4F46E5", button_color: "#F97316", text_color: "#1F2937", footer_text: null };
  let churchName = content.churchName ?? "Your Church";
  if (!b.logo_url && !content.churchName) { const { data: t } = await supabase.from("tenants").select("name").eq("id", tenantId).maybeSingle(); if (t?.name) churchName = t.name; }
  const headerHtml = b.logo_url ? `<img src="${b.logo_url}" alt="${churchName}" style="max-height:60px;max-width:200px;object-fit:contain;" />` : `<span style="color:#ffffff;font-size:22px;font-weight:700;">${churchName}</span>`;
  const ctaHtml = content.ctaLabel && content.ctaUrl ? `<div style="margin:24px 0;"><a href="${content.ctaUrl}" style="display:inline-block;background:${b.button_color};color:#ffffff;padding:12px 28px;border-radius:8px;text-decoration:none;font-weight:600;font-size:14px;">${content.ctaLabel}</a></div>` : "";
  const signatureHtml = (b.sender_photo_url || b.sender_name || b.email_signature) ? `<div style="margin-top:24px;padding-top:16px;border-top:1px solid #e5e7eb;">${b.sender_photo_url ? `<img src="${b.sender_photo_url}" alt="" style="width:40px;height:40px;border-radius:50%;object-fit:cover;" />` : ""}${b.sender_name ? `<p style="margin:4px 0;font-weight:600;font-size:14px;color:${b.text_color};">${b.sender_name}</p>` : ""}${b.email_signature ? `<div style="font-size:13px;color:#6b7280;">${b.email_signature.replace(/\n/g, "<br/>")}</div>` : ""}</div>` : "";
  const footerHtml = b.footer_text ? `<div style="margin-top:24px;padding-top:16px;border-top:1px solid #e5e7eb;font-size:11px;color:#9ca3af;text-align:center;">${b.footer_text.replace(/\n/g, "<br/>")}</div>` : "";
  const html = `<!DOCTYPE html><html><head><meta charset="UTF-8"/><title>${content.subject}</title></head><body style="margin:0;padding:0;background:#f3f4f6;font-family:Arial,sans-serif;"><table width="100%" cellpadding="0" cellspacing="0" style="background:#f3f4f6;padding:32px 16px;"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#ffffff;border-radius:12px;overflow:hidden;"><tr><td style="background:${b.primary_color};padding:28px 32px;text-align:center;">${headerHtml}</td></tr><tr><td style="padding:32px;color:${b.text_color};font-size:15px;line-height:1.7;">${content.body.replace(/\n/g, "<br/>")}${ctaHtml}${signatureHtml}${footerHtml}</td></tr></table></td></tr></table></body></html>`;
  return { html, subject: content.subject };
}
