export type PlatformActor = 'admin' | 'member' | 'public';
export interface PlatformRoute { path: string; actor: PlatformActor; module: string; }
export interface PlatformAction {
  id: string; route: string; actor: PlatformActor; module: string; action: string;
  permission: string; outcome: string; destructive: boolean;
}

export const PLATFORM_ROUTES: PlatformRoute[] = [
  { path: '*', actor: 'public', module: 'Public' },
  { path: '/', actor: 'public', module: 'Public' },
  { path: '/accounts-payable', actor: 'admin', module: 'Platform' },
  { path: '/ai-tools', actor: 'admin', module: 'Platform' },
  { path: '/announcements', actor: 'admin', module: 'Platform' },
  { path: '/appointments', actor: 'admin', module: 'Platform' },
  { path: '/asset-management', actor: 'admin', module: 'Platform' },
  { path: '/auth/callback', actor: 'public', module: 'Public' },
  { path: '/auth/canva/callback', actor: 'public', module: 'Public' },
  { path: '/auth/forgot-password', actor: 'public', module: 'Public' },
  { path: '/auth/invite', actor: 'public', module: 'Public' },
  { path: '/auth/reset-password', actor: 'public', module: 'Public' },
  { path: '/auth/signin', actor: 'public', module: 'Public' },
  { path: '/auth/signup', actor: 'public', module: 'Public' },
  { path: '/bible-explorer', actor: 'admin', module: 'Platform' },
  { path: '/board-meetings', actor: 'admin', module: 'Platform' },
  { path: '/board-meetings/:id/minutes', actor: 'admin', module: 'Platform' },
  { path: '/book/:tenantId', actor: 'public', module: 'Public' },
  { path: '/book/:tenantId/:facilityId', actor: 'public', module: 'Public' },
  { path: '/branches', actor: 'admin', module: 'Platform' },
  { path: '/branches/:branchId', actor: 'admin', module: 'Platform' },
  { path: '/budget-management', actor: 'admin', module: 'Platform' },
  { path: '/childrens-ministry', actor: 'admin', module: 'Platform' },
  { path: '/childrens-ministry/kiosk', actor: 'admin', module: 'Platform' },
  { path: '/church-expenses', actor: 'admin', module: 'Platform' },
  { path: '/church-media', actor: 'admin', module: 'Platform' },
  { path: '/church/:slug', actor: 'public', module: 'Public' },
  { path: '/communications', actor: 'admin', module: 'Platform' },
  { path: '/communications/compose', actor: 'admin', module: 'Platform' },
  { path: '/dashboard', actor: 'admin', module: 'Platform' },
  { path: '/data-compliance', actor: 'admin', module: 'Platform' },
  { path: '/data-policy', actor: 'admin', module: 'Platform' },
  { path: '/design-system', actor: 'admin', module: 'Platform' },
  { path: '/discipleship', actor: 'admin', module: 'Platform' },
  { path: '/discipleship-resources', actor: 'admin', module: 'Platform' },
  { path: '/discipleship/graduates', actor: 'admin', module: 'Platform' },
  { path: '/events', actor: 'admin', module: 'Platform' },
  { path: '/facility-booking', actor: 'admin', module: 'Platform' },
  { path: '/families', actor: 'admin', module: 'Platform' },
  { path: '/families/:id', actor: 'admin', module: 'Platform' },
  { path: '/follow-up-tasks', actor: 'admin', module: 'Platform' },
  { path: '/fund-accounting', actor: 'admin', module: 'Platform' },
  { path: '/general-ledger', actor: 'admin', module: 'Platform' },
  { path: '/give-online', actor: 'admin', module: 'Platform' },
  { path: '/giving-records', actor: 'admin', module: 'Platform' },
  { path: '/graphics-studio', actor: 'admin', module: 'Platform' },
  { path: '/groups', actor: 'admin', module: 'Platform' },
  { path: '/groups/:groupId', actor: 'admin', module: 'Platform' },
  { path: '/house-fellowships', actor: 'admin', module: 'Platform' },
  { path: '/house-fellowships/:fellowshipId', actor: 'admin', module: 'Platform' },
  { path: '/incident-management', actor: 'admin', module: 'Platform' },
  { path: '/join/:joinCode', actor: 'public', module: 'Public' },
  { path: '/livestreaming', actor: 'admin', module: 'Platform' },
  { path: '/member', actor: 'member', module: 'Member Portal' },
  { path: '/member-login', actor: 'member', module: 'Member Portal' },
  { path: '/member-messaging', actor: 'member', module: 'Member Portal' },
  { path: '/member-registration/:orgId', actor: 'member', module: 'Member Portal' },
  { path: '/member-requests', actor: 'member', module: 'Member Portal' },
  { path: '/member/announcements', actor: 'member', module: 'Member Portal' },
  { path: '/member/appointments', actor: 'member', module: 'Member Portal' },
  { path: '/member/bible', actor: 'member', module: 'Member Portal' },
  { path: '/member/children', actor: 'member', module: 'Member Portal' },
  { path: '/member/church-media', actor: 'member', module: 'Member Portal' },
  { path: '/member/church-media/albums/:albumId', actor: 'member', module: 'Member Portal' },
  { path: '/member/events', actor: 'member', module: 'Member Portal' },
  { path: '/member/events/:eventId', actor: 'member', module: 'Member Portal' },
  { path: '/member/facility-booking', actor: 'member', module: 'Member Portal' },
  { path: '/member/give', actor: 'member', module: 'Member Portal' },
  { path: '/member/giving-history', actor: 'member', module: 'Member Portal' },
  { path: '/member/groups', actor: 'member', module: 'Member Portal' },
  { path: '/member/groups/:groupId', actor: 'member', module: 'Member Portal' },
  { path: '/member/house-fellowships', actor: 'member', module: 'Member Portal' },
  { path: '/member/join', actor: 'member', module: 'Member Portal' },
  { path: '/member/livestreaming', actor: 'member', module: 'Member Portal' },
  { path: '/member/login', actor: 'member', module: 'Member Portal' },
  { path: '/member/messages', actor: 'member', module: 'Member Portal' },
  { path: '/member/outreach', actor: 'member', module: 'Member Portal' },
  { path: '/member/pledge-campaigns', actor: 'member', module: 'Member Portal' },
  { path: '/member/profile', actor: 'member', module: 'Member Portal' },
  { path: '/member/profile-setup', actor: 'member', module: 'Member Portal' },
  { path: '/member/requests', actor: 'member', module: 'Member Portal' },
  { path: '/member/sermons', actor: 'member', module: 'Member Portal' },
  { path: '/member/sermons/:sermonId', actor: 'member', module: 'Member Portal' },
  { path: '/member/settings', actor: 'member', module: 'Member Portal' },
  { path: '/member/store', actor: 'member', module: 'Member Portal' },
  { path: '/member/surveys', actor: 'member', module: 'Member Portal' },
  { path: '/member/testimonies', actor: 'member', module: 'Member Portal' },
  { path: '/member/training', actor: 'member', module: 'Member Portal' },
  { path: '/member/training/certificate/:courseId', actor: 'member', module: 'Member Portal' },
  { path: '/member/training/course/:courseId', actor: 'member', module: 'Member Portal' },
  { path: '/member/training/lesson/:lessonId', actor: 'member', module: 'Member Portal' },
  { path: '/member/volunteer', actor: 'member', module: 'Member Portal' },
  { path: '/member/watch-live', actor: 'member', module: 'Member Portal' },
  { path: '/member/welcome', actor: 'member', module: 'Member Portal' },
  { path: '/member/whatsapp', actor: 'member', module: 'Member Portal' },
  { path: '/members', actor: 'member', module: 'Member Portal' },
  { path: '/members/:memberId', actor: 'member', module: 'Member Portal' },
  { path: '/new-converts', actor: 'admin', module: 'Platform' },
  { path: '/onboarding', actor: 'admin', module: 'Platform' },
  { path: '/outreach', actor: 'admin', module: 'Platform' },
  { path: '/outreach/:activityId', actor: 'admin', module: 'Platform' },
  { path: '/payouts', actor: 'admin', module: 'Platform' },
  { path: '/payroll', actor: 'admin', module: 'Platform' },
  { path: '/pledge-campaigns', actor: 'admin', module: 'Platform' },
  { path: '/privacy', actor: 'public', module: 'Public' },
  { path: '/privacy-policy', actor: 'public', module: 'Public' },
  { path: '/quiz/play/:sessionId/:participantId', actor: 'public', module: 'Public' },
  { path: '/quiz/results/:sessionId/:participantId', actor: 'public', module: 'Public' },
  { path: '/quiz/waiting/:sessionId/:participantId', actor: 'public', module: 'Public' },
  { path: '/reports', actor: 'admin', module: 'Platform' },
  { path: '/resources-store', actor: 'admin', module: 'Platform' },
  { path: '/security-centre', actor: 'admin', module: 'Platform' },
  { path: '/sermon-preparation', actor: 'admin', module: 'Platform' },
  { path: '/sermons', actor: 'admin', module: 'Platform' },
  { path: '/sermons/:tenantId', actor: 'public', module: 'Public' },
  { path: '/sermons/:tenantId/:sermonId', actor: 'public', module: 'Public' },
  { path: '/services', actor: 'admin', module: 'Platform' },
  { path: '/settings', actor: 'admin', module: 'Platform' },
  { path: '/song-library', actor: 'admin', module: 'Platform' },
  { path: '/store/:tenantId', actor: 'public', module: 'Public' },
  { path: '/superadmin', actor: 'admin', module: 'Platform' },
  { path: '/superadmin/churches', actor: 'admin', module: 'Platform' },
  { path: '/superadmin/storage-requests', actor: 'admin', module: 'Platform' },
  { path: '/survey/:surveyId', actor: 'public', module: 'Public' },
  { path: '/surveys', actor: 'admin', module: 'Platform' },
  { path: '/surveys/:surveyId/responses', actor: 'admin', module: 'Platform' },
  { path: '/terms', actor: 'public', module: 'Public' },
  { path: '/terms-of-service', actor: 'public', module: 'Public' },
  { path: '/testimonies', actor: 'admin', module: 'Platform' },
  { path: '/training', actor: 'admin', module: 'Platform' },
  { path: '/training/:courseId/edit', actor: 'admin', module: 'Platform' },
  { path: '/training/host/:sessionId', actor: 'admin', module: 'Platform' },
  { path: '/training/host/:sessionId/results', actor: 'admin', module: 'Platform' },
  { path: '/training/new', actor: 'admin', module: 'Platform' },
  { path: '/visitor-registration/:churchId', actor: 'public', module: 'Public' },
  { path: '/visitors', actor: 'admin', module: 'Platform' },
  { path: '/volunteering', actor: 'admin', module: 'Platform' },
  { path: 'access-control', actor: 'admin', module: 'Platform' },
  { path: 'announcement-types', actor: 'admin', module: 'Platform' },
  { path: 'appointment-types', actor: 'admin', module: 'Platform' },
  { path: 'attendance', actor: 'admin', module: 'Platform' },
  { path: 'backup', actor: 'admin', module: 'Platform' },
  { path: 'billing', actor: 'admin', module: 'Platform' },
  { path: 'branches', actor: 'admin', module: 'Platform' },
  { path: 'checkin', actor: 'admin', module: 'Platform' },
  { path: 'children', actor: 'admin', module: 'Platform' },
  { path: 'classes', actor: 'admin', module: 'Platform' },
  { path: 'communications-settings', actor: 'admin', module: 'Platform' },
  { path: 'contact', actor: 'admin', module: 'Platform' },
  { path: 'facility-types', actor: 'admin', module: 'Platform' },
  { path: 'general', actor: 'admin', module: 'Platform' },
  { path: 'giving', actor: 'admin', module: 'Platform' },
  { path: 'group-types', actor: 'admin', module: 'Platform' },
  { path: 'integrations', actor: 'admin', module: 'Platform' },
  { path: 'legal', actor: 'admin', module: 'Platform' },
  { path: 'livestreaming', actor: 'admin', module: 'Platform' },
  { path: 'media-categories', actor: 'admin', module: 'Platform' },
  { path: 'member-app', actor: 'admin', module: 'Platform' },
  { path: 'modules', actor: 'admin', module: 'Platform' },
  { path: 'notifications', actor: 'admin', module: 'Platform' },
  { path: 'payments', actor: 'admin', module: 'Platform' },
  { path: 'preferences', actor: 'admin', module: 'Platform' },
  { path: 'privacy', actor: 'admin', module: 'Platform' },
  { path: 'profile', actor: 'admin', module: 'Platform' },
  { path: 'qr-codes', actor: 'admin', module: 'Platform' },
  { path: 'registration', actor: 'admin', module: 'Platform' },
  { path: 'reports', actor: 'admin', module: 'Platform' },
  { path: 'roles', actor: 'admin', module: 'Platform' },
  { path: 'security', actor: 'admin', module: 'Platform' },
  { path: 'seo', actor: 'admin', module: 'Platform' },
  { path: 'service-requests', actor: 'admin', module: 'Platform' },
  { path: 'services', actor: 'admin', module: 'Platform' },
  { path: 'settings', actor: 'admin', module: 'Platform' },
  { path: 'staff', actor: 'admin', module: 'Platform' },
  { path: 'tax', actor: 'admin', module: 'Platform' },
  { path: 'testimony-categories', actor: 'admin', module: 'Platform' },
  { path: 'users', actor: 'admin', module: 'Platform' },
  { path: 'vision', actor: 'admin', module: 'Platform' },
  { path: 'website', actor: 'admin', module: 'Platform' },
];

export const PLATFORM_ACTIONS: PlatformAction[] = [
  { id: 'members-create', route: '/members', actor: 'admin', module: 'People', action: 'create member', permission: 'members.create', outcome: 'member row belongs to current tenant', destructive: true },
  { id: 'members-export', route: '/members', actor: 'admin', module: 'People', action: 'export CSV', permission: 'members.export', outcome: 'download excludes foreign tenant rows', destructive: false },
  { id: 'volunteer-export', route: '/volunteering', actor: 'admin', module: 'Operations', action: 'export volunteer data', permission: 'volunteering.read', outcome: 'download reflects tenant/date filters', destructive: false },
  { id: 'announcement-create', route: '/announcements', actor: 'admin', module: 'Engagement', action: 'publish announcement', permission: 'communications.create', outcome: 'audience receives tenant-scoped announcement', destructive: true },
  { id: 'survey-create', route: '/surveys', actor: 'admin', module: 'Engagement', action: 'create survey', permission: 'communications.create', outcome: 'survey belongs to tenant', destructive: true },
  { id: 'qr-copy', route: '/settings/access-control', actor: 'admin', module: 'Settings', action: 'copy QR URL', permission: 'settings.read', outcome: 'URL encodes current tenant hostname', destructive: false },
  { id: 'member-request', route: '/member/requests', actor: 'member', module: 'Member Portal', action: 'submit request', permission: 'member.self', outcome: 'request tenant/member identity derived from session', destructive: true },
  { id: 'subscription-upgrade', route: '/settings/billing', actor: 'admin', module: 'Billing', action: 'start STK', permission: 'billing.manage', outcome: 'server catalog determines amount', destructive: true },
];
