export type PlatformActor = 'admin' | 'member' | 'public';
export interface PlatformRoute { path: string; actor: PlatformActor; module: string; }
export type ActionRisk = 'critical' | 'high' | 'medium' | 'low';
export type ActionVerification = 'automated' | 'protected-e2e' | 'manual-exception';
export interface PlatformAction {
  id: string; route: string; actor: PlatformActor; module: string; action: string;
  permission: string; outcome: string; destructive: boolean; risk: ActionRisk;
  verification: ActionVerification; testRef: string; manualReason?: string;
}

export const PLATFORM_ROUTES: PlatformRoute[] = [
  { path: '*', actor: 'public', module: 'Public' },
  { path: '/', actor: 'public', module: 'Public' },
  { path: '/accounts-payable', actor: 'admin', module: 'Platform' },
  { path: '/ai-tools', actor: 'admin', module: 'Platform' },
  { path: '/announcements', actor: 'admin', module: 'Platform' },
  { path: '/appointments', actor: 'admin', module: 'Platform' },
  { path: '/asset-management', actor: 'admin', module: 'Platform' },
  { path: '/auth/callback', actor: 'public', module: 'Public' },
  { path: '/auth/canva/callback', actor: 'public', module: 'Public' },
  { path: '/auth/forgot-password', actor: 'public', module: 'Public' },
  { path: '/auth/invite', actor: 'public', module: 'Public' },
  { path: '/auth/reset-password', actor: 'public', module: 'Public' },
  { path: '/auth/signin', actor: 'public', module: 'Public' },
  { path: '/auth/signup', actor: 'public', module: 'Public' },
  { path: '/bible-explorer', actor: 'admin', module: 'Platform' },
  { path: '/board-meetings', actor: 'admin', module: 'Platform' },
  { path: '/board-meetings/:id/minutes', actor: 'admin', module: 'Platform' },
  { path: '/book/:tenantId', actor: 'public', module: 'Public' },
  { path: '/book/:tenantId/:facilityId', actor: 'public', module: 'Public' },
  { path: '/branches', actor: 'admin', module: 'Platform' },
  { path: '/branches/:branchId', actor: 'admin', module: 'Platform' },
  { path: '/budget-management', actor: 'admin', module: 'Platform' },
  { path: '/childrens-ministry', actor: 'admin', module: 'Platform' },
  { path: '/childrens-ministry/kiosk', actor: 'admin', module: 'Platform' },
  { path: '/church-expenses', actor: 'admin', module: 'Platform' },
  { path: '/church-media', actor: 'admin', module: 'Platform' },
  { path: '/church/:slug', actor: 'public', module: 'Public' },
  { path: '/communications', actor: 'admin', module: 'Platform' },
  { path: '/communications/compose', actor: 'admin', module: 'Platform' },
  { path: '/dashboard', actor: 'admin', module: 'Platform' },
  { path: '/data-compliance', actor: 'admin', module: 'Platform' },
  { path: '/data-policy', actor: 'admin', module: 'Platform' },
  { path: '/design-system', actor: 'admin', module: 'Platform' },
  { path: '/discipleship', actor: 'admin', module: 'Platform' },
  { path: '/discipleship-resources', actor: 'admin', module: 'Platform' },
  { path: '/discipleship/graduates', actor: 'admin', module: 'Platform' },
  { path: '/events', actor: 'admin', module: 'Platform' },
  { path: '/facility-booking', actor: 'admin', module: 'Platform' },
  { path: '/families', actor: 'admin', module: 'Platform' },
  { path: '/families/:id', actor: 'admin', module: 'Platform' },
  { path: '/follow-up-tasks', actor: 'admin', module: 'Platform' },
  { path: '/fund-accounting', actor: 'admin', module: 'Platform' },
  { path: '/general-ledger', actor: 'admin', module: 'Platform' },
  { path: '/give-online', actor: 'admin', module: 'Platform' },
  { path: '/giving-records', actor: 'admin', module: 'Platform' },
  { path: '/graphics-studio', actor: 'admin', module: 'Platform' },
  { path: '/groups', actor: 'admin', module: 'Platform' },
  { path: '/groups/:groupId', actor: 'admin', module: 'Platform' },
  { path: '/house-fellowships', actor: 'admin', module: 'Platform' },
  { path: '/house-fellowships/:fellowshipId', actor: 'admin', module: 'Platform' },
  { path: '/incident-management', actor: 'admin', module: 'Platform' },
  { path: '/join/:joinCode', actor: 'public', module: 'Public' },
  { path: '/livestreaming', actor: 'admin', module: 'Platform' },
  { path: '/member', actor: 'member', module: 'Member Portal' },
  { path: '/member-login', actor: 'member', module: 'Member Portal' },
  { path: '/member-messaging', actor: 'member', module: 'Member Portal' },
  { path: '/member-registration/:orgId', actor: 'member', module: 'Member Portal' },
  { path: '/member-requests', actor: 'member', module: 'Member Portal' },
  { path: '/member/announcements', actor: 'member', module: 'Member Portal' },
  { path: '/member/appointments', actor: 'member', module: 'Member Portal' },
  { path: '/member/bible', actor: 'member', module: 'Member Portal' },
  { path: '/member/children', actor: 'member', module: 'Member Portal' },
  { path: '/member/church-media', actor: 'member', module: 'Member Portal' },
  { path: '/member/church-media/albums/:albumId', actor: 'member', module: 'Member Portal' },
  { path: '/member/events', actor: 'member', module: 'Member Portal' },
  { path: '/member/events/:eventId', actor: 'member', module: 'Member Portal' },
  { path: '/member/facility-booking', actor: 'member', module: 'Member Portal' },
  { path: '/member/give', actor: 'member', module: 'Member Portal' },
  { path: '/member/giving-history', actor: 'member', module: 'Member Portal' },
  { path: '/member/groups', actor: 'member', module: 'Member Portal' },
  { path: '/member/groups/:groupId', actor: 'member', module: 'Member Portal' },
  { path: '/member/house-fellowships', actor: 'member', module: 'Member Portal' },
  { path: '/member/join', actor: 'member', module: 'Member Portal' },
  { path: '/member/livestreaming', actor: 'member', module: 'Member Portal' },
  { path: '/member/login', actor: 'member', module: 'Member Portal' },
  { path: '/member/messages', actor: 'member', module: 'Member Portal' },
  { path: '/member/outreach', actor: 'member', module: 'Member Portal' },
  { path: '/member/pledge-campaigns', actor: 'member', module: 'Member Portal' },
  { path: '/member/profile', actor: 'member', module: 'Member Portal' },
  { path: '/member/profile-setup', actor: 'member', module: 'Member Portal' },
  { path: '/member/requests', actor: 'member', module: 'Member Portal' },
  { path: '/member/sermons', actor: 'member', module: 'Member Portal' },
  { path: '/member/sermons/:sermonId', actor: 'member', module: 'Member Portal' },
  { path: '/member/settings', actor: 'member', module: 'Member Portal' },
  { path: '/member/store', actor: 'member', module: 'Member Portal' },
  { path: '/member/surveys', actor: 'member', module: 'Member Portal' },
  { path: '/member/testimonies', actor: 'member', module: 'Member Portal' },
  { path: '/member/training', actor: 'member', module: 'Member Portal' },
  { path: '/member/training/certificate/:courseId', actor: 'member', module: 'Member Portal' },
  { path: '/member/training/course/:courseId', actor: 'member', module: 'Member Portal' },
  { path: '/member/training/lesson/:lessonId', actor: 'member', module: 'Member Portal' },
  { path: '/member/volunteer', actor: 'member', module: 'Member Portal' },
  { path: '/member/watch-live', actor: 'member', module: 'Member Portal' },
  { path: '/member/welcome', actor: 'member', module: 'Member Portal' },
  { path: '/member/whatsapp', actor: 'member', module: 'Member Portal' },
  { path: '/members', actor: 'member', module: 'Member Portal' },
  { path: '/members/:memberId', actor: 'member', module: 'Member Portal' },
  { path: '/new-converts', actor: 'admin', module: 'Platform' },
  { path: '/onboarding', actor: 'admin', module: 'Platform' },
  { path: '/outreach', actor: 'admin', module: 'Platform' },
  { path: '/outreach/:activityId', actor: 'admin', module: 'Platform' },
  { path: '/payouts', actor: 'admin', module: 'Platform' },
  { path: '/payroll', actor: 'admin', module: 'Platform' },
  { path: '/pledge-campaigns', actor: 'admin', module: 'Platform' },
  { path: '/privacy', actor: 'public', module: 'Public' },
  { path: '/privacy-policy', actor: 'public', module: 'Public' },
  { path: '/quiz/play/:sessionId/:participantId', actor: 'public', module: 'Public' },
  { path: '/quiz/results/:sessionId/:participantId', actor: 'public', module: 'Public' },
  { path: '/quiz/waiting/:sessionId/:participantId', actor: 'public', module: 'Public' },
  { path: '/reports', actor: 'admin', module: 'Platform' },
  { path: '/resources-store', actor: 'admin', module: 'Platform' },
  { path: '/security-centre', actor: 'admin', module: 'Platform' },
  { path: '/sermon-preparation', actor: 'admin', module: 'Platform' },
  { path: '/sermons', actor: 'admin', module: 'Platform' },
  { path: '/sermons/:tenantId', actor: 'public', module: 'Public' },
  { path: '/sermons/:tenantId/:sermonId', actor: 'public', module: 'Public' },
  { path: '/services', actor: 'admin', module: 'Platform' },
  { path: '/settings', actor: 'admin', module: 'Platform' },
  { path: '/song-library', actor: 'admin', module: 'Platform' },
  { path: '/store/:tenantId', actor: 'public', module: 'Public' },
  { path: '/superadmin', actor: 'admin', module: 'Platform' },
  { path: '/superadmin/churches', actor: 'admin', module: 'Platform' },
  { path: '/superadmin/storage-requests', actor: 'admin', module: 'Platform' },
  { path: '/survey/:surveyId', actor: 'public', module: 'Public' },
  { path: '/surveys', actor: 'admin', module: 'Platform' },
  { path: '/surveys/:surveyId/responses', actor: 'admin', module: 'Platform' },
  { path: '/terms', actor: 'public', module: 'Public' },
  { path: '/terms-of-service', actor: 'public', module: 'Public' },
  { path: '/testimonies', actor: 'admin', module: 'Platform' },
  { path: '/training', actor: 'admin', module: 'Platform' },
  { path: '/training/:courseId/edit', actor: 'admin', module: 'Platform' },
  { path: '/training/host/:sessionId', actor: 'admin', module: 'Platform' },
  { path: '/training/host/:sessionId/results', actor: 'admin', module: 'Platform' },
  { path: '/training/new', actor: 'admin', module: 'Platform' },
  { path: '/visitor-registration/:churchId', actor: 'public', module: 'Public' },
  { path: '/visitors', actor: 'admin', module: 'Platform' },
  { path: '/volunteering', actor: 'admin', module: 'Platform' },
  { path: 'access-control', actor: 'admin', module: 'Platform' },
  { path: 'announcement-types', actor: 'admin', module: 'Platform' },
  { path: 'appointment-types', actor: 'admin', module: 'Platform' },
  { path: 'attendance', actor: 'admin', module: 'Platform' },
  { path: 'backup', actor: 'admin', module: 'Platform' },
  { path: 'billing', actor: 'admin', module: 'Platform' },
  { path: 'branches', actor: 'admin', module: 'Platform' },
  { path: 'checkin', actor: 'admin', module: 'Platform' },
  { path: 'children', actor: 'admin', module: 'Platform' },
  { path: 'classes', actor: 'admin', module: 'Platform' },
  { path: 'communications-settings', actor: 'admin', module: 'Platform' },
  { path: 'contact', actor: 'admin', module: 'Platform' },
  { path: 'facility-types', actor: 'admin', module: 'Platform' },
  { path: 'general', actor: 'admin', module: 'Platform' },
  { path: 'giving', actor: 'admin', module: 'Platform' },
  { path: 'group-types', actor: 'admin', module: 'Platform' },
  { path: 'integrations', actor: 'admin', module: 'Platform' },
  { path: 'legal', actor: 'admin', module: 'Platform' },
  { path: 'livestreaming', actor: 'admin', module: 'Platform' },
  { path: 'media-categories', actor: 'admin', module: 'Platform' },
  { path: 'member-app', actor: 'admin', module: 'Platform' },
  { path: 'modules', actor: 'admin', module: 'Platform' },
  { path: 'notifications', actor: 'admin', module: 'Platform' },
  { path: 'payments', actor: 'admin', module: 'Platform' },
  { path: 'preferences', actor: 'admin', module: 'Platform' },
  { path: 'privacy', actor: 'admin', module: 'Platform' },
  { path: 'profile', actor: 'admin', module: 'Platform' },
  { path: 'qr-codes', actor: 'admin', module: 'Platform' },
  { path: 'registration', actor: 'admin', module: 'Platform' },
  { path: 'reports', actor: 'admin', module: 'Platform' },
  { path: 'roles', actor: 'admin', module: 'Platform' },
  { path: 'security', actor: 'admin', module: 'Platform' },
  { path: 'seo', actor: 'admin', module: 'Platform' },
  { path: 'service-requests', actor: 'admin', module: 'Platform' },
  { path: 'services', actor: 'admin', module: 'Platform' },
  { path: 'settings', actor: 'admin', module: 'Platform' },
  { path: 'staff', actor: 'admin', module: 'Platform' },
  { path: 'tax', actor: 'admin', module: 'Platform' },
  { path: 'testimony-categories', actor: 'admin', module: 'Platform' },
  { path: 'users', actor: 'admin', module: 'Platform' },
  { path: 'vision', actor: 'admin', module: 'Platform' },
  { path: 'website', actor: 'admin', module: 'Platform' },
];

export const PLATFORM_ACTIONS: PlatformAction[] = [
  { id: 'members-create', route: '/members', actor: 'admin', module: 'People', action: 'create member', permission: 'members.create', outcome: 'member belongs to current tenant', destructive: true, risk: 'high', verification: 'automated', testRef: 'e2e/platform/permissions.spec.ts + tenant-boundary.spec.ts' },
  { id: 'members-update', route: '/members/:memberId', actor: 'admin', module: 'People', action: 'update member', permission: 'members.update', outcome: 'only current-tenant member is updated', destructive: true, risk: 'high', verification: 'protected-e2e', testRef: 'stage7: member CRUD workflow' },
  { id: 'members-delete', route: '/members/:memberId', actor: 'admin', module: 'People', action: 'delete member', permission: 'members.delete', outcome: 'delete cannot cross tenant boundary', destructive: true, risk: 'critical', verification: 'protected-e2e', testRef: 'stage7: member CRUD workflow' },
  { id: 'members-import', route: '/members', actor: 'admin', module: 'People', action: 'import members CSV', permission: 'members.create', outcome: 'valid rows import tenant-scoped; invalid/duplicate rows reported', destructive: true, risk: 'high', verification: 'automated', testRef: 'e2e/platform/import-export.spec.ts' },
  { id: 'members-export', route: '/members', actor: 'admin', module: 'People', action: 'export members CSV', permission: 'members.export', outcome: 'download excludes foreign tenant rows', destructive: false, risk: 'medium', verification: 'automated', testRef: 'e2e/platform/import-export.spec.ts' },
  { id: 'visitor-create', route: '/visitors', actor: 'admin', module: 'People', action: 'create visitor', permission: 'visitors.create', outcome: 'visitor belongs to current tenant', destructive: true, risk: 'high', verification: 'protected-e2e', testRef: 'stage7: people workflows' },
  { id: 'visitor-convert', route: '/visitors', actor: 'admin', module: 'People', action: 'convert visitor to new convert', permission: 'visitors.update', outcome: 'conversion is tenant-scoped and idempotent', destructive: true, risk: 'high', verification: 'protected-e2e', testRef: 'stage7: people workflows' },
  { id: 'family-create', route: '/families', actor: 'admin', module: 'People', action: 'create family', permission: 'families.create', outcome: 'family belongs to current tenant', destructive: true, risk: 'medium', verification: 'protected-e2e', testRef: 'stage7: people workflows' },
  { id: 'family-link-member', route: '/families/:id', actor: 'admin', module: 'People', action: 'link member to family', permission: 'families.update', outcome: 'only same-tenant members can be linked', destructive: true, risk: 'high', verification: 'protected-e2e', testRef: 'stage7: people workflows' },
  { id: 'followup-create', route: '/follow-up-tasks', actor: 'admin', module: 'People', action: 'create follow-up task', permission: 'followups.create', outcome: 'task relationships stay tenant-scoped', destructive: true, risk: 'medium', verification: 'protected-e2e', testRef: 'stage7: people workflows' },
  { id: 'event-create', route: '/events', actor: 'admin', module: 'Operations', action: 'create event', permission: 'events.create', outcome: 'event belongs to tenant', destructive: true, risk: 'high', verification: 'protected-e2e', testRef: 'stage7: operations workflows' },
  { id: 'event-update', route: '/events', actor: 'admin', module: 'Operations', action: 'edit event', permission: 'events.update', outcome: 'only current-tenant event changes', destructive: true, risk: 'high', verification: 'protected-e2e', testRef: 'stage7: operations workflows' },
  { id: 'event-rsvp-admin', route: '/events', actor: 'admin', module: 'Operations', action: 'record event attendance/RSVP', permission: 'events.update', outcome: 'attendance is linked to correct tenant event/member', destructive: true, risk: 'high', verification: 'protected-e2e', testRef: 'stage7: operations workflows' },
  { id: 'service-create', route: '/services', actor: 'admin', module: 'Operations', action: 'schedule service', permission: 'services.create', outcome: 'service belongs to tenant', destructive: true, risk: 'high', verification: 'protected-e2e', testRef: 'stage7: operations workflows' },
  { id: 'service-attendance', route: '/services', actor: 'admin', module: 'Operations', action: 'record service attendance', permission: 'attendance.create', outcome: 'attendance cannot reference foreign tenant people', destructive: true, risk: 'high', verification: 'protected-e2e', testRef: 'stage7: operations workflows' },
  { id: 'volunteer-role-create', route: '/volunteering', actor: 'admin', module: 'Operations', action: 'create volunteer role/opportunity', permission: 'volunteering.create', outcome: 'opportunity belongs to tenant', destructive: true, risk: 'medium', verification: 'protected-e2e', testRef: 'stage7: operations workflows' },
  { id: 'volunteer-assign', route: '/volunteering', actor: 'admin', module: 'Operations', action: 'assign volunteer', permission: 'volunteering.update', outcome: 'assignment stays within tenant', destructive: true, risk: 'high', verification: 'protected-e2e', testRef: 'stage7: operations workflows' },
  { id: 'volunteer-export', route: '/volunteering', actor: 'admin', module: 'Operations', action: 'export volunteer data', permission: 'volunteering.read', outcome: 'download reflects tenant/date filters', destructive: false, risk: 'medium', verification: 'automated', testRef: 'P1 operations contract + stage7 UI' },
  { id: 'board-meeting-create', route: '/board-meetings', actor: 'admin', module: 'Operations', action: 'create board meeting', permission: 'board_meetings.create', outcome: 'meeting is staff-only and tenant-scoped', destructive: true, risk: 'high', verification: 'protected-e2e', testRef: 'stage7: operations workflows' },
  { id: 'board-minutes-save', route: '/board-meetings/:id/minutes', actor: 'admin', module: 'Operations', action: 'save meeting minutes/decisions', permission: 'board_meetings.update', outcome: 'minutes and decisions remain tenant-scoped', destructive: true, risk: 'high', verification: 'protected-e2e', testRef: 'stage7: operations workflows' },
  { id: 'facility-share-link', route: '/facility-booking', actor: 'admin', module: 'Operations', action: 'copy public booking link', permission: 'facilities.read', outcome: 'URL references the current tenant', destructive: false, risk: 'low', verification: 'protected-e2e', testRef: 'stage7: share-link checks' },
  { id: 'facility-booking-review', route: '/facility-booking', actor: 'admin', module: 'Operations', action: 'approve or decline booking', permission: 'facilities.update', outcome: 'status change is atomic and tenant-scoped', destructive: true, risk: 'high', verification: 'protected-e2e', testRef: 'stage7: operations workflows' },
  { id: 'announcement-create', route: '/announcements', actor: 'admin', module: 'Engagement', action: 'publish announcement', permission: 'communications.create', outcome: 'audience receives tenant-scoped announcement', destructive: true, risk: 'high', verification: 'protected-e2e', testRef: 'stage7: engagement workflows' },
  { id: 'announcement-edit', route: '/announcements', actor: 'admin', module: 'Engagement', action: 'edit announcement', permission: 'communications.update', outcome: 'only tenant announcement changes', destructive: true, risk: 'medium', verification: 'protected-e2e', testRef: 'stage7: engagement workflows' },
  { id: 'announcement-delete', route: '/announcements', actor: 'admin', module: 'Engagement', action: 'delete announcement', permission: 'communications.delete', outcome: 'delete cannot cross tenant boundary', destructive: true, risk: 'high', verification: 'protected-e2e', testRef: 'stage7: engagement workflows' },
  { id: 'survey-create', route: '/surveys', actor: 'admin', module: 'Engagement', action: 'create survey', permission: 'communications.create', outcome: 'survey belongs to tenant', destructive: true, risk: 'high', verification: 'protected-e2e', testRef: 'stage7: engagement workflows' },
  { id: 'survey-share', route: '/surveys', actor: 'admin', module: 'Engagement', action: 'copy survey share link', permission: 'communications.read', outcome: 'link resolves to selected tenant survey', destructive: false, risk: 'low', verification: 'protected-e2e', testRef: 'stage7: share-link checks' },
  { id: 'survey-delete', route: '/surveys', actor: 'admin', module: 'Engagement', action: 'delete survey', permission: 'communications.delete', outcome: 'delete stays tenant-scoped', destructive: true, risk: 'high', verification: 'protected-e2e', testRef: 'stage7: engagement workflows' },
  { id: 'appointment-review', route: '/appointments', actor: 'admin', module: 'Engagement', action: 'confirm/decline/reschedule appointment', permission: 'appointments.update', outcome: 'appointment status cannot cross tenant', destructive: true, risk: 'high', verification: 'protected-e2e', testRef: 'stage7: engagement workflows' },
  { id: 'testimony-moderate', route: '/testimonies', actor: 'admin', module: 'Engagement', action: 'approve/reject testimony', permission: 'testimonies.update', outcome: 'moderation is tenant-scoped', destructive: true, risk: 'high', verification: 'protected-e2e', testRef: 'stage7: engagement workflows' },
  { id: 'message-send-admin', route: '/member-messaging', actor: 'admin', module: 'Messaging', action: 'send participant message', permission: 'messaging.send', outcome: 'only conversation participants receive message', destructive: true, risk: 'critical', verification: 'protected-e2e', testRef: 'stage7: messaging workflows' },
  { id: 'message-delete-admin', route: '/member-messaging', actor: 'admin', module: 'Messaging', action: 'delete message', permission: 'messaging.delete', outcome: 'only authorized participant/staff deletion succeeds', destructive: true, risk: 'high', verification: 'protected-e2e', testRef: 'stage7: messaging workflows' },
  { id: 'message-attachment-admin', route: '/member-messaging', actor: 'admin', module: 'Messaging', action: 'upload message attachment', permission: 'messaging.send', outcome: 'signed attachment stays participant-only', destructive: true, risk: 'critical', verification: 'protected-e2e', testRef: 'stage7: messaging attachment workflow' },
  { id: 'giving-record-create', route: '/giving-records', actor: 'admin', module: 'Finance', action: 'record giving transaction', permission: 'giving.create', outcome: 'amount/member/payment metadata stored in tenant', destructive: true, risk: 'critical', verification: 'protected-e2e', testRef: 'stage7: finance workflows' },
  { id: 'giving-export', route: '/giving-records', actor: 'admin', module: 'Finance', action: 'export giving records', permission: 'giving.read', outcome: 'export contains current tenant records only', destructive: false, risk: 'high', verification: 'protected-e2e', testRef: 'stage7: finance export' },
  { id: 'expense-create', route: '/church-expenses', actor: 'admin', module: 'Finance', action: 'record expense', permission: 'expenses.create', outcome: 'expense belongs to tenant', destructive: true, risk: 'critical', verification: 'protected-e2e', testRef: 'stage7: finance workflows' },
  { id: 'expense-approve', route: '/church-expenses', actor: 'admin', module: 'Finance', action: 'approve expense', permission: 'expenses.approve', outcome: 'approval requires permission and current tenant', destructive: true, risk: 'critical', verification: 'protected-e2e', testRef: 'stage7: finance permission matrix' },
  { id: 'budget-create', route: '/budget-management', actor: 'admin', module: 'Finance', action: 'create budget', permission: 'budgets.create', outcome: 'budget and categories stay tenant-scoped', destructive: true, risk: 'high', verification: 'protected-e2e', testRef: 'stage7: finance workflows' },
  { id: 'accounts-payable-create', route: '/accounts-payable', actor: 'admin', module: 'Finance', action: 'create payable', permission: 'finance.create', outcome: 'payable belongs to tenant', destructive: true, risk: 'high', verification: 'protected-e2e', testRef: 'stage7: finance workflows' },
  { id: 'pledge-campaign-create', route: '/pledge-campaigns', actor: 'admin', module: 'Finance', action: 'create pledge campaign', permission: 'giving.create', outcome: 'campaign belongs to tenant', destructive: true, risk: 'high', verification: 'protected-e2e', testRef: 'stage7: finance workflows' },
  { id: 'payroll-run', route: '/payroll', actor: 'admin', module: 'Finance', action: 'create/process payroll run', permission: 'payroll.manage', outcome: 'payroll cannot affect foreign tenant staff', destructive: true, risk: 'critical', verification: 'manual-exception', testRef: 'manual: external payroll/payment side effects are not safe for shared automated QA', manualReason: 'requires isolated finance sandbox and provider stubs' },
  { id: 'communications-email-send', route: '/communications/compose', actor: 'admin', module: 'Communications', action: 'queue email broadcast', permission: 'communications.send', outcome: 'queue job is tenant-scoped and idempotent', destructive: true, risk: 'critical', verification: 'protected-e2e', testRef: 'stage7: queue-backed communications' },
  { id: 'communications-sms-send', route: '/communications', actor: 'admin', module: 'Communications', action: 'queue SMS broadcast', permission: 'communications.send', outcome: 'queue job is tenant-scoped and credit-safe', destructive: true, risk: 'critical', verification: 'protected-e2e', testRef: 'stage7: queue-backed communications' },
  { id: 'communications-template-save', route: '/communications', actor: 'admin', module: 'Communications', action: 'save communication template', permission: 'communications.update', outcome: 'template belongs to tenant', destructive: true, risk: 'medium', verification: 'protected-e2e', testRef: 'stage7: communications workflows' },
  { id: 'settings-modules-save', route: '/settings/modules', actor: 'admin', module: 'Settings', action: 'save enabled modules', permission: 'settings.update', outcome: 'canonical module configuration persists', destructive: true, risk: 'high', verification: 'automated', testRef: 'src/test/p1/modules + e2e/platform/modules/module-enforcement.spec.ts' },
  { id: 'settings-member-app-save', route: '/settings/member-app', actor: 'admin', module: 'Settings', action: 'save member portal features', permission: 'settings.update', outcome: 'member features remain bounded by admin modules', destructive: true, risk: 'high', verification: 'automated', testRef: 'src/test/p1/modules + Stage 3 module QA' },
  { id: 'settings-user-invite', route: '/settings/users', actor: 'admin', module: 'Settings', action: 'invite staff user', permission: 'users.create', outcome: 'invite belongs to tenant and respects role permissions', destructive: true, risk: 'critical', verification: 'protected-e2e', testRef: 'stage7: permissions workflows' },
  { id: 'settings-permissions-save', route: '/settings/access-control', actor: 'admin', module: 'Settings', action: 'change role/user permissions', permission: 'settings.permissions', outcome: 'permission changes cannot grant cross-tenant access', destructive: true, risk: 'critical', verification: 'protected-e2e', testRef: 'stage7: permission matrix + direct DB denial' },
  { id: 'qr-copy', route: '/settings/access-control', actor: 'admin', module: 'Settings', action: 'copy QR URL', permission: 'settings.read', outcome: 'URL encodes current tenant hostname', destructive: false, risk: 'medium', verification: 'protected-e2e', testRef: 'stage7: QR/share-link checks' },
  { id: 'subscription-upgrade', route: '/settings/billing', actor: 'admin', module: 'Billing', action: 'start subscription STK', permission: 'billing.manage', outcome: 'server catalog determines amount and callback is idempotent', destructive: true, risk: 'critical', verification: 'manual-exception', testRef: 'manual: requires disposable payment credentials/provider sandbox and callback validation', manualReason: 'run against isolated M-Pesa sandbox only' },
  { id: 'member-rsvp', route: '/member/events/:eventId', actor: 'member', module: 'Member Portal', action: 'RSVP to event', permission: 'member.self', outcome: 'RSVP derives member/tenant identity from session', destructive: true, risk: 'high', verification: 'protected-e2e', testRef: 'stage7: member workflows' },
  { id: 'member-message-send', route: '/member/messages', actor: 'member', module: 'Member Portal', action: 'send message', permission: 'member.self', outcome: 'only participant conversation can receive message', destructive: true, risk: 'critical', verification: 'protected-e2e', testRef: 'stage7: messaging workflows' },
  { id: 'member-message-attachment', route: '/member/messages', actor: 'member', module: 'Member Portal', action: 'upload message attachment', permission: 'member.self', outcome: 'attachment remains participant-only', destructive: true, risk: 'critical', verification: 'protected-e2e', testRef: 'stage7: messaging attachment workflow' },
  { id: 'member-request', route: '/member/requests', actor: 'member', module: 'Member Portal', action: 'submit request', permission: 'member.self', outcome: 'request tenant/member identity derived from session', destructive: true, risk: 'high', verification: 'protected-e2e', testRef: 'stage7: member workflows' },
  { id: 'member-appointment', route: '/member/appointments', actor: 'member', module: 'Member Portal', action: 'book appointment', permission: 'member.self', outcome: 'appointment derives tenant/member from validated session', destructive: true, risk: 'high', verification: 'protected-e2e', testRef: 'stage7: member workflows' },
  { id: 'member-testimony', route: '/member/testimonies', actor: 'member', module: 'Member Portal', action: 'submit testimony', permission: 'member.self', outcome: 'testimony derives tenant/member from session', destructive: true, risk: 'high', verification: 'protected-e2e', testRef: 'stage7: member workflows' },
  { id: 'member-volunteer-signup', route: '/member/volunteer', actor: 'member', module: 'Member Portal', action: 'sign up to volunteer', permission: 'member.self', outcome: 'signup stays within tenant opportunity/capacity', destructive: true, risk: 'high', verification: 'protected-e2e', testRef: 'stage7: member workflows' },
  { id: 'member-facility-book', route: '/member/facility-booking', actor: 'member', module: 'Member Portal', action: 'request facility booking', permission: 'member.self', outcome: 'booking derives current tenant/member', destructive: true, risk: 'high', verification: 'protected-e2e', testRef: 'stage7: member workflows' },
  { id: 'member-give-stk', route: '/member/give', actor: 'member', module: 'Member Portal', action: 'initiate church giving STK', permission: 'member.self', outcome: 'church giving uses church payment path, not platform subscription billing', destructive: true, risk: 'critical', verification: 'manual-exception', testRef: 'manual: requires church-specific disposable M-Pesa sandbox credentials and callback verification', manualReason: 'keep separate from subscription billing QA' },
  { id: 'member-profile-update', route: '/member/profile', actor: 'member', module: 'Member Portal', action: 'update own profile', permission: 'member.self', outcome: 'member can update only own allowed fields', destructive: true, risk: 'high', verification: 'protected-e2e', testRef: 'stage7: member workflows' },
  { id: 'member-settings-update', route: '/member/settings', actor: 'member', module: 'Member Portal', action: 'update notification/preferences', permission: 'member.self', outcome: 'member changes only own preferences', destructive: true, risk: 'medium', verification: 'protected-e2e', testRef: 'stage7: member workflows' },
  { id: 'member-survey-submit', route: '/member/surveys', actor: 'member', module: 'Member Portal', action: 'submit survey response', permission: 'member.self', outcome: 'response belongs to current tenant/member', destructive: true, risk: 'medium', verification: 'protected-e2e', testRef: 'stage7: member workflows' },
  { id: 'public-survey-submit', route: '/survey/:surveyId', actor: 'public', module: 'Public', action: 'submit public survey', permission: 'public', outcome: 'response is bound to survey tenant and validation rules', destructive: true, risk: 'medium', verification: 'protected-e2e', testRef: 'stage7: public workflows' },
  { id: 'public-facility-book', route: '/book/:tenantId/:facilityId', actor: 'public', module: 'Public', action: 'submit public facility booking', permission: 'public', outcome: 'tenant/facility identifiers are validated server-side', destructive: true, risk: 'high', verification: 'protected-e2e', testRef: 'stage7: public workflows' },
  { id: 'public-visitor-register', route: '/visitor-registration/:churchId', actor: 'public', module: 'Public', action: 'register visitor', permission: 'public', outcome: 'visitor is created only in target tenant', destructive: true, risk: 'high', verification: 'protected-e2e', testRef: 'stage7: public workflows' },
  { id: 'public-member-register', route: '/member-registration/:orgId', actor: 'public', module: 'Public', action: 'register member', permission: 'public', outcome: 'membership request targets selected tenant only', destructive: true, risk: 'high', verification: 'protected-e2e', testRef: 'stage7: public workflows' },
];

export const PLATFORM_ACTION_SUMMARY = PLATFORM_ACTIONS.reduce((acc, item) => {
  acc.total += 1;
  acc[item.actor] += 1;
  acc[item.risk] += 1;
  acc[item.verification] += 1;
  return acc;
}, { total: 0, admin: 0, member: 0, public: 0, critical: 0, high: 0, medium: 0, low: 0, automated: 0, 'protected-e2e': 0, 'manual-exception': 0 } as Record<string, number>);
