export const PLANS = {
  free: {
    name: 'Free',
    price: 0,
    priceLabel: 'Free forever',
    color: '#64748b',
    member_limit: 100,
    staff_limit: 3,
    branch_limit: 1,
    storage_limit_gb: 2,
    sms_credits: 0,
    email_credits: 100,
    ai_credits: 0,
    mpesa_giving: false,
    sermon_ai: false,
    features: ['100 members', '3 staff accounts', '1 branch', '2GB storage', '100 emails lifetime', 'Member portal', 'Manual giving only'],
  },
  basic: {
    name: 'Basic',
    price: 2499,
    priceLabel: 'KSh 2,499/mo',
    color: '#0ea5e9',
    member_limit: 200,
    staff_limit: 7,
    branch_limit: 3,
    storage_limit_gb: 10,
    sms_credits: 100,
    email_credits: 500,
    ai_credits: 0,
    mpesa_giving: true,
    sermon_ai: false,
    features: ['200 members', '7 staff accounts', '3 branches', '10GB storage', '100 SMS/month', '500 emails/month', 'M-Pesa giving', 'Member portal'],
  },
  growth: {
    name: 'Growth',
    price: 8999,
    priceLabel: 'KSh 8,999/mo',
    color: '#7c3aed',
    member_limit: 500,
    staff_limit: 15,
    branch_limit: 10,
    storage_limit_gb: 20,
    sms_credits: 500,
    email_credits: 2000,
    ai_credits: 50,
    mpesa_giving: true,
    sermon_ai: true,
    features: ['500 members', '15 staff accounts', '10 branches', '20GB storage', '500 SMS/month', '2,000 emails/month', '50 AI credits/month', 'M-Pesa giving', 'Sermon AI', 'Priority support'],
  },
  pro: {
    name: 'Pro',
    price: 12499,
    priceLabel: 'KSh 12,499/mo',
    color: '#f97316',
    member_limit: 2000,
    staff_limit: 30,
    branch_limit: 20,
    storage_limit_gb: 50,
    sms_credits: 2000,
    email_credits: 8000,
    ai_credits: 200,
    mpesa_giving: true,
    sermon_ai: true,
    features: ['2,000 members', '30 staff accounts', '20 branches', '50GB storage', '2,000 SMS/month', '8,000 emails/month', '200 AI credits/month', 'M-Pesa giving', 'Sermon AI', 'Priority support', 'Dedicated account manager'],
  },
} as const;

export const ADD_ONS = [
  { key: 'member_addons', label: 'Extra Members', unit: '100 members', price: 500, amount: 100, icon: '👥' },
  { key: 'sms_addons', label: 'Extra SMS', unit: '100 SMS credits', price: 100, amount: 100, icon: '📱' },
  { key: 'email_addons', label: 'Extra Emails', unit: '500 emails', price: 100, amount: 500, icon: '📧' },
  { key: 'ai_addons', label: 'Extra AI Credits', unit: '20 AI credits', price: 300, amount: 20, icon: '🤖' },
  { key: 'storage_addons_gb', label: 'Extra Storage', unit: '5GB storage', price: 200, amount: 5, icon: '🗄' },
] as const;