ALTER TABLE branches ADD COLUMN IF NOT EXISTS branch_username VARCHAR;
ALTER TABLE branches ADD COLUMN IF NOT EXISTS branch_password_hash VARCHAR;
ALTER TABLE branches ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ;
