ALTER TABLE tenants
  ADD COLUMN IF NOT EXISTS early_riser_time TEXT NOT NULL DEFAULT '06:00',
  ADD COLUMN IF NOT EXISTS morning_service_time TEXT NOT NULL DEFAULT '10:00',
  ADD COLUMN IF NOT EXISTS afternoon_service_time TEXT NOT NULL DEFAULT '14:00',
  ADD COLUMN IF NOT EXISTS fiscal_year_start_month INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS member_id_prefix TEXT NOT NULL DEFAULT 'MEM',
  ADD COLUMN IF NOT EXISTS auto_generate_member_ids BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS enable_checkin BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS allow_self_checkout BOOLEAN NOT NULL DEFAULT true;
