ALTER TABLE tenants ADD COLUMN IF NOT EXISTS post_code VARCHAR;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS senior_pastor VARCHAR;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS app_slug VARCHAR;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS require_post_code BOOLEAN DEFAULT false;;
