ALTER TABLE family_members
  ADD COLUMN IF NOT EXISTS first_name VARCHAR,
  ADD COLUMN IF NOT EXISTS middle_name VARCHAR,
  ADD COLUMN IF NOT EXISTS last_name VARCHAR,
  ADD COLUMN IF NOT EXISTS suffix VARCHAR,
  ADD COLUMN IF NOT EXISTS gender VARCHAR,
  ADD COLUMN IF NOT EXISTS role VARCHAR DEFAULT 'member',
  ADD COLUMN IF NOT EXISTS birth_month INTEGER,
  ADD COLUMN IF NOT EXISTS birth_day INTEGER,
  ADD COLUMN IF NOT EXISTS birth_year INTEGER,
  ADD COLUMN IF NOT EXISTS classification VARCHAR DEFAULT 'member';
