-- Add missing columns to sermons table for Sermon Preparation and Sermons & Messages features

-- Add media columns
ALTER TABLE sermons ADD COLUMN IF NOT EXISTS thumbnail_url TEXT;
ALTER TABLE sermons ADD COLUMN IF NOT EXISTS thumbnail_path TEXT;
ALTER TABLE sermons ADD COLUMN IF NOT EXISTS video_url TEXT;
ALTER TABLE sermons ADD COLUMN IF NOT EXISTS audio_url TEXT;
ALTER TABLE sermons ADD COLUMN IF NOT EXISTS audio_file_path TEXT;
ALTER TABLE sermons ADD COLUMN IF NOT EXISTS doc_file_path TEXT;

-- Add sermon preparation columns
ALTER TABLE sermons ADD COLUMN IF NOT EXISTS sermon_type TEXT DEFAULT 'sermon';
ALTER TABLE sermons ADD COLUMN IF NOT EXISTS style TEXT;
ALTER TABLE sermons ADD COLUMN IF NOT EXISTS audience TEXT;
ALTER TABLE sermons ADD COLUMN IF NOT EXISTS duration TEXT;
ALTER TABLE sermons ADD COLUMN IF NOT EXISTS draft_notes TEXT;
ALTER TABLE sermons ADD COLUMN IF NOT EXISTS additional_instructions TEXT;
ALTER TABLE sermons ADD COLUMN IF NOT EXISTS manuscript TEXT;
ALTER TABLE sermons ADD COLUMN IF NOT EXISTS ai_generated BOOLEAN DEFAULT false;

-- Add status column if not exists
ALTER TABLE sermons ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'draft';

-- Add sermon date if not exists
ALTER TABLE sermons ADD COLUMN IF NOT EXISTS sermon_date DATE;

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_sermons_tenant_status ON sermons(tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_sermons_tenant_published ON sermons(tenant_id, is_published);
CREATE INDEX IF NOT EXISTS idx_sermons_sermon_date ON sermons(sermon_date);

-- Add comment
COMMENT ON COLUMN sermons.thumbnail_url IS 'Public URL for sermon thumbnail image';
COMMENT ON COLUMN sermons.audio_file_path IS 'Storage path for audio file in private bucket';
COMMENT ON COLUMN sermons.doc_file_path IS 'Storage path for document file in private bucket';
COMMENT ON COLUMN sermons.sermon_type IS 'Type: sermon or bible_study';
COMMENT ON COLUMN sermons.style IS 'Preaching style: expository, topical, narrative, etc.';
COMMENT ON COLUMN sermons.ai_generated IS 'Whether this sermon was generated by AI';
COMMENT ON COLUMN sermons.status IS 'Status: draft, ready, published, or archived';
