CREATE INDEX IF NOT EXISTS idx_members_tenant ON members(tenant_id);
CREATE INDEX IF NOT EXISTS idx_members_tenant_created ON members(tenant_id, created_at);
CREATE INDEX IF NOT EXISTS idx_users_tenant_status ON users(tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_events_tenant_date ON events(tenant_id, event_date);
CREATE INDEX IF NOT EXISTS idx_events_tenant_published ON events(tenant_id, is_published);
CREATE INDEX IF NOT EXISTS idx_groups_tenant_active ON groups(tenant_id, is_active);
CREATE INDEX IF NOT EXISTS idx_announcements_tenant ON announcements(tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_new_converts_tenant ON new_converts(tenant_id);
CREATE INDEX IF NOT EXISTS idx_giving_records_tenant ON giving_records(tenant_id, given_at DESC);
CREATE INDEX IF NOT EXISTS idx_visitors_tenant ON visitors(tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_follow_up_tasks_tenant ON follow_up_tasks(tenant_id);
CREATE INDEX IF NOT EXISTS idx_services_tenant ON services(tenant_id);
CREATE INDEX IF NOT EXISTS idx_testimonies_tenant ON testimonies(tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_member_requests_tenant ON member_requests(tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_conversations_tenant ON conversations(tenant_id);
CREATE INDEX IF NOT EXISTS idx_studio_media_tenant ON studio_media(tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_outreach_activities_tenant ON outreach_activities(tenant_id);
CREATE INDEX IF NOT EXISTS idx_training_courses_tenant ON training_courses(tenant_id);
CREATE INDEX IF NOT EXISTS idx_training_enrollments_course ON training_enrollments(course_id);
CREATE INDEX IF NOT EXISTS idx_group_members_group ON group_members(group_id);
CREATE INDEX IF NOT EXISTS idx_group_members_member ON group_members(member_id);
CREATE INDEX IF NOT EXISTS idx_event_rsvps_event ON event_rsvps(event_id);
CREATE INDEX IF NOT EXISTS idx_event_rsvps_member ON event_rsvps(member_id);;
